[2025-07-24T14:46:11.622+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T06:00:00+00:00 [queued]>
[2025-07-24T14:46:11.638+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T06:00:00+00:00 [queued]>
[2025-07-24T14:46:11.639+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T14:46:11.689+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-04 06:00:00+00:00
[2025-07-24T14:46:11.704+0000] {standard_task_runner.py:60} INFO - Started process 542 to run task
[2025-07-24T14:46:11.710+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-04T06:00:00+00:00', '--job-id', '682', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpaxs1xzah']
[2025-07-24T14:46:11.717+0000] {standard_task_runner.py:88} INFO - Job 682: Subtask Load_songplays_fact_table
[2025-07-24T14:46:11.906+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T06:00:00+00:00 [running]> on host aea62fae55be
[2025-07-24T14:46:12.124+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-04T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-04T06:00:00+00:00'
[2025-07-24T14:46:12.131+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 170, in <lambda>
    python_callable=lambda: load_table(SqlQueries.songplay_table_insert),
TypeError: load_table() missing 1 required positional argument: 'table'
[2025-07-24T14:46:12.172+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230104T060000, start_date=20250724T144611, end_date=20250724T144612
[2025-07-24T14:46:12.203+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 682 for task Load_songplays_fact_table (load_table() missing 1 required positional argument: 'table'; 542)
[2025-07-24T14:46:12.246+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T14:46:12.275+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T17:30:13.294+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T06:00:00+00:00 [queued]>
[2025-07-24T17:30:13.303+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T06:00:00+00:00 [queued]>
[2025-07-24T17:30:13.304+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T17:30:13.320+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-04 06:00:00+00:00
[2025-07-24T17:30:13.328+0000] {standard_task_runner.py:60} INFO - Started process 2878 to run task
[2025-07-24T17:30:13.336+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-04T06:00:00+00:00', '--job-id', '2501', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp65pjf2gl']
[2025-07-24T17:30:13.341+0000] {standard_task_runner.py:88} INFO - Job 2501: Subtask Load_songplays_fact_table
[2025-07-24T17:30:13.449+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T06:00:00+00:00 [running]> on host 5def55d2a1b5
[2025-07-24T17:30:14.243+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-04T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-04T06:00:00+00:00'
[2025-07-24T17:30:53.334+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-24T17:30:53.359+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230104T060000, start_date=20250724T173013, end_date=20250724T173053
[2025-07-24T17:30:53.731+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-24T17:30:53.760+0000] {taskinstance.py:3280} INFO - 4 downstream tasks scheduled from follow-on schedule check
