[2025-07-24T14:45:55.281+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T03:00:00+00:00 [queued]>
[2025-07-24T14:45:55.431+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T03:00:00+00:00 [queued]>
[2025-07-24T14:45:55.435+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T14:45:55.478+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-04 03:00:00+00:00
[2025-07-24T14:45:55.500+0000] {standard_task_runner.py:60} INFO - Started process 516 to run task
[2025-07-24T14:45:55.521+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-04T03:00:00+00:00', '--job-id', '672', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpi064umxa']
[2025-07-24T14:45:55.531+0000] {standard_task_runner.py:88} INFO - Job 672: Subtask Load_songplays_fact_table
[2025-07-24T14:45:55.827+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T03:00:00+00:00 [running]> on host aea62fae55be
[2025-07-24T14:45:59.899+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-04T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-04T03:00:00+00:00'
[2025-07-24T14:45:59.904+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 170, in <lambda>
    python_callable=lambda: load_table(SqlQueries.songplay_table_insert),
TypeError: load_table() missing 1 required positional argument: 'table'
[2025-07-24T14:46:00.053+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230104T030000, start_date=20250724T144555, end_date=20250724T144600
[2025-07-24T14:46:00.743+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 672 for task Load_songplays_fact_table (load_table() missing 1 required positional argument: 'table'; 516)
[2025-07-24T14:46:01.107+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T14:46:01.875+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T17:30:27.164+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T03:00:00+00:00 [queued]>
[2025-07-24T17:30:27.178+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T03:00:00+00:00 [queued]>
[2025-07-24T17:30:27.179+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T17:30:27.238+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-04 03:00:00+00:00
[2025-07-24T17:30:27.248+0000] {standard_task_runner.py:60} INFO - Started process 2892 to run task
[2025-07-24T17:30:27.255+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-04T03:00:00+00:00', '--job-id', '2506', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpb0_w48z1']
[2025-07-24T17:30:27.258+0000] {standard_task_runner.py:88} INFO - Job 2506: Subtask Load_songplays_fact_table
[2025-07-24T17:30:27.418+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-04T03:00:00+00:00 [running]> on host 5def55d2a1b5
[2025-07-24T17:30:27.684+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-04T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-04T03:00:00+00:00'
[2025-07-24T17:30:56.709+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-24T17:30:56.783+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230104T030000, start_date=20250724T173027, end_date=20250724T173056
[2025-07-24T17:30:57.411+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-24T17:30:57.442+0000] {taskinstance.py:3280} INFO - 4 downstream tasks scheduled from follow-on schedule check
