[2025-07-24T18:13:07.167+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.data_quality_checks scheduled__2023-01-10T09:00:00+00:00 [queued]>
[2025-07-24T18:13:07.201+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.data_quality_checks scheduled__2023-01-10T09:00:00+00:00 [queued]>
[2025-07-24T18:13:07.205+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T18:13:07.467+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): data_quality_checks> on 2023-01-10 09:00:00+00:00
[2025-07-24T18:13:07.493+0000] {standard_task_runner.py:60} INFO - Started process 7289 to run task
[2025-07-24T18:13:07.502+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'data_quality_checks', 'scheduled__2023-01-10T09:00:00+00:00', '--job-id', '3781', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpbmd4v6i5']
[2025-07-24T18:13:07.506+0000] {standard_task_runner.py:88} INFO - Job 3781: Subtask data_quality_checks
[2025-07-24T18:13:07.638+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.data_quality_checks scheduled__2023-01-10T09:00:00+00:00 [running]> on host 5def55d2a1b5
[2025-07-24T18:13:07.790+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2023-01-10T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-10T09:00:00+00:00'
[2025-07-24T18:13:07.802+0000] {logging_mixin.py:188} INFO - songplays passed check: is not empty
[2025-07-24T18:13:07.804+0000] {logging_mixin.py:188} INFO - users passed check: is not empty
[2025-07-24T18:13:07.805+0000] {logging_mixin.py:188} INFO - songs passed check: is not empty
[2025-07-24T18:13:07.806+0000] {logging_mixin.py:188} INFO - artists passed check: is not empty
[2025-07-24T18:13:07.808+0000] {logging_mixin.py:188} INFO - time passed check: is not empty
[2025-07-24T18:13:07.810+0000] {logging_mixin.py:188} INFO - songplays passed check: has no NULL playid
[2025-07-24T18:13:07.811+0000] {logging_mixin.py:188} INFO - users passed check: has no NULL userid
[2025-07-24T18:13:07.812+0000] {logging_mixin.py:188} INFO - songs passed check: has no NULL songid
[2025-07-24T18:13:07.813+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 168, in check_quality
    cur.execute(query)
psycopg2.errors.UndefinedColumn: column "artist_id" does not exist
LINE 1: SELECT COUNT(*) FROM artists WHERE artist_id IS NULL
                                           ^
HINT:  Perhaps you meant to reference the column "artists.artistid".

[2025-07-24T18:13:07.828+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_stream_dag, task_id=data_quality_checks, execution_date=20230110T090000, start_date=20250724T181307, end_date=20250724T181307
[2025-07-24T18:13:07.856+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3781 for task data_quality_checks (column "artist_id" does not exist
LINE 1: SELECT COUNT(*) FROM artists WHERE artist_id IS NULL
                                           ^
HINT:  Perhaps you meant to reference the column "artists.artistid".
; 7289)
[2025-07-24T18:13:07.881+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T18:13:07.916+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
